apiVersion: kubewise.io/v1alpha1
kind: Consolidate
metadata:
  name: consolidate-m6i
  description: "Consolidate all non-GPU nodes to m6i.xlarge (max 50 nodes)"
spec:
  target_node_type: m6i.xlarge
  max_nodes: 50
  keep_node_pools:
    - gpu-pool
