// Copyright 2026 Arsene Tochemey Gandote
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package output

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/tochemey/kubewise/pkg/risk"
)

func TestRenderMarkdownContainsTitle(t *testing.T) {
	var buf bytes.Buffer
	err := RenderMarkdown(&buf, newTestReport())
	require.NoError(t, err)

	assert.Contains(t, buf.String(), "## KubeWise: Right-size simulation")
}

func TestRenderMarkdownContainsDescription(t *testing.T) {
	var buf bytes.Buffer
	err := RenderMarkdown(&buf, newTestReport())
	require.NoError(t, err)

	assert.Contains(t, buf.String(), "Right-size simulation (p95 + 20% buffer)")
}

func TestRenderMarkdownContainsSummaryTable(t *testing.T) {
	var buf bytes.Buffer
	err := RenderMarkdown(&buf, newTestReport())
	require.NoError(t, err)

	output := buf.String()
	assert.Contains(t, output, "| Metric | Value |")
	assert.Contains(t, output, "Current monthly cost")
	assert.Contains(t, output, "Projected monthly cost")
	assert.Contains(t, output, "Savings")
	assert.Contains(t, output, "$14230")
	assert.Contains(t, output, "$9840")
	assert.Contains(t, output, "$4390")
	assert.Contains(t, output, "30.8%")
}

func TestRenderMarkdownContainsRiskInfo(t *testing.T) {
	var buf bytes.Buffer
	err := RenderMarkdown(&buf, newTestReport())
	require.NoError(t, err)

	output := buf.String()
	assert.Contains(t, output, "OOM risk")
	assert.Contains(t, output, "0.8%")
	assert.Contains(t, output, "Overall risk")
}

func TestRenderMarkdownContainsCollapsibleNamespaces(t *testing.T) {
	var buf bytes.Buffer
	err := RenderMarkdown(&buf, newTestReport())
	require.NoError(t, err)

	output := buf.String()
	assert.Contains(t, output, "<details>")
	assert.Contains(t, output, "</details>")
	assert.Contains(t, output, "<summary>Savings by namespace</summary>")
	assert.Contains(t, output, "api")
	assert.Contains(t, output, "data-pipeline")
	assert.Contains(t, output, "default")
}

func TestRenderMarkdownContainsNamespaceTable(t *testing.T) {
	var buf bytes.Buffer
	err := RenderMarkdown(&buf, newTestReport())
	require.NoError(t, err)

	output := buf.String()
	assert.Contains(t, output, "| Namespace | Savings | Risk |")
	assert.Contains(t, output, "$1200")
}

func TestRenderMarkdownContainsFooter(t *testing.T) {
	var buf bytes.Buffer
	err := RenderMarkdown(&buf, newTestReport())
	require.NoError(t, err)

	assert.Contains(t, buf.String(), "Generated by KubeWise")
}

func TestRenderMarkdownContainsRiskEmojis(t *testing.T) {
	var buf bytes.Buffer
	report := newTestReport()
	report.NamespaceBreakdown = append(report.NamespaceBreakdown, NamespaceSummary{
		Namespace: "risky-ns", Savings: 500, RiskLevel: risk.RiskRed,
	})

	err := RenderMarkdown(&buf, report)
	require.NoError(t, err)

	output := buf.String()
	assert.Contains(t, output, "🟢")
	assert.Contains(t, output, "🟡")
	assert.Contains(t, output, "🔴")
}

func TestRenderMarkdownVerboseShowsWorkloads(t *testing.T) {
	var buf bytes.Buffer
	report := newTestReport()
	report.Verbose = true
	report.NamespaceBreakdown[0].Workloads = []WorkloadSummary{
		{Name: "api-gateway", Savings: 800, RiskLevel: risk.RiskGreen},
	}

	err := RenderMarkdown(&buf, report)
	require.NoError(t, err)

	output := buf.String()
	assert.Contains(t, output, "Workload details")
	assert.Contains(t, output, "api-gateway")
}

func TestRenderMarkdownNonVerboseHidesWorkloads(t *testing.T) {
	var buf bytes.Buffer
	report := newTestReport()
	report.Verbose = false
	report.NamespaceBreakdown[0].Workloads = []WorkloadSummary{
		{Name: "hidden-workload", Savings: 100, RiskLevel: risk.RiskGreen},
	}

	err := RenderMarkdown(&buf, report)
	require.NoError(t, err)

	assert.NotContains(t, buf.String(), "hidden-workload")
}

func TestRenderMarkdownEmptyNamespaces(t *testing.T) {
	var buf bytes.Buffer
	report := newTestReport()
	report.NamespaceBreakdown = nil

	err := RenderMarkdown(&buf, report)
	require.NoError(t, err)

	assert.NotContains(t, buf.String(), "<details>")
	assert.Contains(t, buf.String(), "Generated by KubeWise")
}

func TestMdRiskBadge(t *testing.T) {
	assert.Equal(t, "🟢 low", mdRiskBadge(risk.RiskGreen))
	assert.Equal(t, "🟡 moderate", mdRiskBadge(risk.RiskAmber))
	assert.Equal(t, "🔴 high", mdRiskBadge(risk.RiskRed))
	assert.Equal(t, "⚪ unknown", mdRiskBadge(risk.RiskUnknown))
}
