// Copyright 2026 KubeWise Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package output

import (
	"fmt"
	"io"
	"strings"

	"github.com/tochemey/kubewise/pkg/risk"
)

// RenderMarkdown writes the report as Markdown suitable for GitHub PR comments.
func RenderMarkdown(w io.Writer, report Report) error {
	var sb strings.Builder

	// Title
	fmt.Fprintf(&sb, "## KubeWise: %s\n\n", report.ScenarioName)
	if report.ScenarioDesc != "" {
		fmt.Fprintf(&sb, "_%s_\n\n", report.ScenarioDesc)
	}

	// Summary table
	sb.WriteString("| Metric | Value |\n")
	sb.WriteString("|--------|-------|\n")
	fmt.Fprintf(&sb, "| Current monthly cost | %s |\n", formatCost(report.BaselineCost))
	fmt.Fprintf(&sb, "| Projected monthly cost | %s |\n", formatCost(report.ProjectedCost))
	fmt.Fprintf(&sb, "| **Savings** | **%s/mo (%.1f%%)** |\n", formatCost(report.Savings), report.SavingsPercent)
	fmt.Fprintf(&sb, "| Cluster OOM risk | %.1f%% %s |\n", report.Risk.ClusterOOM*100, mdRiskEmoji(classifyOOMLevel(report.Risk.ClusterOOM)))
	fmt.Fprintf(&sb, "| Overall risk | %s |\n", mdRiskBadge(report.Risk.OverallLevel))
	sb.WriteString("\n")

	// Namespace breakdown in collapsible sections
	if len(report.NamespaceBreakdown) > 0 {
		sb.WriteString("<details>\n")
		sb.WriteString("<summary>Savings by namespace</summary>\n\n")
		sb.WriteString("| Namespace | Savings | Risk |\n")
		sb.WriteString("|-----------|---------|------|\n")
		for _, ns := range report.NamespaceBreakdown {
			fmt.Fprintf(&sb, "| %s | %s/mo | %s |\n",
				ns.Namespace,
				formatCost(ns.Savings),
				mdRiskBadge(ns.RiskLevel),
			)
		}

		// Per-workload details if verbose
		if report.Verbose {
			sb.WriteString("\n### Workload details\n\n")
			sb.WriteString("| Namespace | Workload | Savings | Risk |\n")
			sb.WriteString("|-----------|----------|---------|------|\n")
			for _, ns := range report.NamespaceBreakdown {
				for _, wl := range ns.Workloads {
					fmt.Fprintf(&sb, "| %s | %s | %s/mo | %s |\n",
						ns.Namespace,
						wl.Name,
						formatCost(wl.Savings),
						mdRiskBadge(wl.RiskLevel),
					)
				}
			}
		}

		sb.WriteString("\n</details>\n\n")
	}

	// Footer
	sb.WriteString("---\n")
	sb.WriteString("Generated by KubeWise\n")

	_, err := fmt.Fprint(w, sb.String())
	return err
}

// mdRiskEmoji returns a risk emoji for markdown.
func mdRiskEmoji(level risk.RiskLevel) string {
	switch level {
	case risk.RiskGreen:
		return "🟢"
	case risk.RiskAmber:
		return "🟡"
	case risk.RiskRed:
		return "🔴"
	default:
		return "⚪"
	}
}

// mdRiskBadge returns a risk badge string for markdown tables.
func mdRiskBadge(level risk.RiskLevel) string {
	switch level {
	case risk.RiskGreen:
		return "🟢 low"
	case risk.RiskAmber:
		return "🟡 moderate"
	case risk.RiskRed:
		return "🔴 high"
	case risk.RiskUnknown:
		return "⚪ unknown"
	default:
		return "⚪ unknown"
	}
}
