// Copyright 2026 KubeWise Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build integration

package main

import (
	"bytes"
	"encoding/json"
	"os/exec"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func buildBinary(t *testing.T) string {
	t.Helper()
	binary := t.TempDir() + "/kubectl-whatif"
	cmd := exec.Command("go", "build", "-o", binary, "./")
	cmd.Dir = "../../cmd/kubectl-whatif"
	out, err := cmd.CombinedOutput()
	require.NoError(t, err, "build failed: %s", string(out))
	return binary
}

func runCLI(t *testing.T, binary string, args ...string) (string, error) {
	t.Helper()
	allArgs := append([]string{"--context=kind-kubewise-test", "--no-color"}, args...)
	cmd := exec.Command(binary, allArgs...)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	err := cmd.Run()
	return stdout.String() + stderr.String(), err
}

func TestIntegrationCLISnapshot(t *testing.T) {
	binary := buildBinary(t)

	output, err := runCLI(t, binary, "snapshot")
	require.NoError(t, err, "snapshot command failed: %s", output)

	assert.Contains(t, output, "KubeWise")
	assert.Contains(t, output, "Current")
}

func TestIntegrationCLISnapshotJSON(t *testing.T) {
	binary := buildBinary(t)

	output, err := runCLI(t, binary, "snapshot", "--output=json")
	require.NoError(t, err, "snapshot --output=json failed: %s", output)

	// Should be valid JSON
	var result map[string]any
	require.NoError(t, json.Unmarshal([]byte(output), &result), "output is not valid JSON: %s", output)

	assert.Contains(t, result, "scenario")
	assert.Contains(t, result, "cost")
}

func TestIntegrationCLISnapshotMarkdown(t *testing.T) {
	binary := buildBinary(t)

	output, err := runCLI(t, binary, "snapshot", "--output=markdown")
	require.NoError(t, err, "snapshot --output=markdown failed: %s", output)

	assert.Contains(t, output, "## KubeWise")
	assert.Contains(t, output, "Generated by KubeWise")
}

func TestIntegrationCLIRightsize(t *testing.T) {
	binary := buildBinary(t)

	output, err := runCLI(t, binary, "rightsize", "--percentile=p95", "--buffer=20")
	require.NoError(t, err, "rightsize command failed: %s", output)

	assert.Contains(t, output, "KubeWise")
	assert.Contains(t, output, "Right-size")
}

func TestIntegrationCLIRightsizeJSON(t *testing.T) {
	binary := buildBinary(t)

	output, err := runCLI(t, binary, "rightsize", "--output=json")
	require.NoError(t, err, "rightsize --output=json failed: %s", output)

	var result map[string]any
	require.NoError(t, json.Unmarshal([]byte(output), &result), "output is not valid JSON")

	assert.Contains(t, result, "scenario")
	assert.Contains(t, result, "risk")
}

func TestIntegrationCLIVersion(t *testing.T) {
	binary := buildBinary(t)

	cmd := exec.Command(binary, "version")
	out, err := cmd.CombinedOutput()
	require.NoError(t, err)

	assert.Contains(t, string(out), "kubectl-whatif")
	assert.Contains(t, string(out), "go version")
}
